"""Build the Markdown companion into public/. Run from any directory."""
from pathlib import Path
import shutil
import markdown

ROOT = Path(__file__).resolve().parent


def main():
    output = ROOT / "public"
    downloads = {
        "git-in-five-minutes.pdf": ROOT / "slides/git-in-five-minutes.pdf",
    }
    for source in downloads.values():
        if not source.is_file():
            raise SystemExit(f"Required download missing: {source.relative_to(ROOT)}")
    content = markdown.markdown(
        (ROOT / "site/index.md").read_text(encoding="utf-8"),
        extensions=["fenced_code", "tables", "attr_list", "md_in_html"],
        output_format="html",
    )
    template = (ROOT / "site/template.html").read_text(encoding="utf-8")
    if template.count("{{content}}") != 1:
        raise SystemExit("Template must contain exactly one {{content}} marker")
    (output / "downloads").mkdir(parents=True, exist_ok=True)
    (output / "index.html").write_text(template.replace("{{content}}", content), encoding="utf-8")
    shutil.copy2(ROOT / "site/style.css", output / "style.css")
    (output / ".nojekyll").touch()
    for name, source in downloads.items():
        shutil.copy2(source, output / "downloads" / name)
    # Remove only obsolete downloads generated by earlier versions of this build.
    for obsolete in ("git-in-five-minutes.tex", "manuscript.tex", "demo-transcript.txt", "slides-source.zip"):
        (output / "downloads" / obsolete).unlink(missing_ok=True)
    print(f"Built {output / 'index.html'}")


if __name__ == "__main__":
    main()
